version: "3.9"
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"

  ngrok:
    build:
      context: .
      args:
        - ARCH=amd64/
    depends_on:
      - web
    command: http web:80 --log stdout

